syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "_AquariumDivingDungeonSettleInfoOuterClass";

import "_AquariumDivingBagDetail.proto";
import "_AquariumDivingLevelEvent.proto";

message _AquariumDivingDungeonSettleInfo {
	uint32 IHODOKLDAGG = 50000;
	_AquariumDivingBagDetail _bag_detail = 10;
	uint32 EFPBHJOIBJH = 6;
	uint32 CFPHMDCAGDL = 50001;
	uint32 _bait_count = 13;
	repeated uint32 _finished_task_id_list = 14;
	_AquariumDivingLevelEvent IDPMJLBKBNC = 3;
	uint32 GJFKPLMNGED = 50002;
}
