syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "_AquariumDetailInfoOuterClass";

import "IIOFHFIDENJ.proto";
import "Uint32Pair.proto";
import "_AquariumDivingLevelEvent.proto";
import "_AquariumDivingTaskInfo.proto";

message _AquariumDetailInfo {
	repeated uint32 MDCCIIFACFK = 50000;
	uint32 DGJCEMANOCM = 50001;
	repeated uint32 GCCOJAGHNKJ = 50002;
	repeated Uint32Pair item_count_list = 14;
	repeated _AquariumDivingTaskInfo task_list = 10;
	repeated Uint32Pair FKCIFOHLLBM = 1;
	repeated uint32 OIECMONFHBM = 50003;
	bool LABPMPANIDK = 50004;
	uint32 FOPBJKEMJPF = 50005;
	uint32 IMDGIKDEBOD = 50006;
	bool PHIFBJJBPLK = 50007;
	uint32 stage_id = 6;
	bool AKNKPOEJHBO = 50008;
	uint32 NAOEDFPLOAE = 50009;
	uint32 EDMCKBNOELC = 50010;
	repeated uint32 PAEGHMOCAME = 50011;
	repeated _AquariumDivingLevelEvent PCJNHLNMKFL = 178;
	uint32 JMBAEDIMHFN = 50012;
	bool OAOKCCGGMGB = 50013;
	repeated uint32 PMJLEBGOILE = 50014;
	repeated IIOFHFIDENJ FLPPKAACIAA = 50015;
	repeated uint32 HFGLFBIEAAM = 50016;
}
