syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "_AutochessRecordSocialBriefOuterClass";

import "KHFBAMPCPPF.proto";
import "Uint32Pair.proto";

message _AutochessRecordSocialBrief {
	repeated uint32 _artifact_id_list = 10;
	uint32 coin = 9;
	repeated uint32 HDKMGJJKEMA = 1;
	bool NBCEKJJNAHJ = 14;
	uint32 timestamp = 3;
	uint32 GBAIFJIKOON = 12;
	uint32 HOAOJBKJFLE = 5;
	uint32 AFDKEOOHHPA = 13;
	uint32 hp = 15;
	KHFBAMPCPPF DNBEJHIILMM = 4;
	uint32 LKPNNFDCJLF = 7;
	uint32 max_hp = 2;
	Uint32Pair progress = 6;
}
