// Recovered from _ClientPlayTypeOuterClass.java's embedded descriptor; wire schema may predate 7.1.
syntax = "proto3";

package recovered.p__ClientPlayType;
option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "_ClientPlayTypeOuterClass";

enum _ClientPlayType {
  CLIENT_PLAY_NONE_TYPE = 0;
  CLIENT_PLAY_FILMFEST_SHOOTING_TYPE = 1;
  CLIENT_PLAY_COOK_GAME_TYPE = 2;
  CLIENT_PLAY_LAN_V4_PUSH_BOX_TYPE = 3;
  CLIENT_PLAY_CATCAFE_LAYOUT_TYPE = 4;
  CLIENT_PLAY_CATCAFE_CAT_TYPE = 5;
  CLIENT_PLAY_GREAT_FESTIVAL_V2_SHEET_RESTORE_TYPE = 6;
  CLIENT_PLAY_BIRD_BALL_TYPE = 7;
  CLIENT_PLAY_FAIRY_TALES_FLYPPY_HAT_TOY_TYPE = 8;
  CLIENT_PLAY_NAHIDA_BIRTH_FLOAT_TOY_TYPE = 9;
  CLIENT_PLAY_CEREMONY_DOODLE_TYPE = 10;
  CLIENT_PLAY_LAN_V5_CARD_TYPE = 12;
  CLIENT_PLAY_LAN_V5_CARD_NPC_LEVEL_TYPE = 13;
  CLIENT_PLAY_DREAM_SWITCHING = 14;
  CLIENT_PLAY_NATLAN_DRILL_COLLECT = 15;
  CLIENT_PLAY_HOLIDAY_RESORT_ADVENTURE = 16;
  CLIENT_PLAY_AUTOCHESS_FRUIT_PICK = 17;
  CLIENT_PLAY_LAN_V6_DANMAKU = 18;
  CLIENT_PLAY_PAINTING_REPAIR_V2 = 19;
  CLIENT_PLAY_LOLI_JUMP = 20;
  CLIENT_PLAY_AQUARIUM_SELL = 21;
}
