syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "_CooperateChallengeSettleInfoOuterClass";

import "ExhibitionDisplayInfo.proto";
import "ProfilePicture.proto";

message _CooperateChallengeSettleInfo {
	enum EACPNCPOKGE {
		EACPNCPOKGE_SETTLE_REASON_NONE = 0;
		EACPNCPOKGE_SETTLE_REASON_SUCC = 1;
		EACPNCPOKGE_SETTLE_REASON_PLAYER_NOT_ENOUGH = 2;
	}
	message FGCJMIDEKMB {
		repeated uint32 uid_list = 11;
		uint32 FAFDNMIEMEL = 13;
		int32 EOAFEBOFEJB = 12;
	}
	message JOPDICINNLJ {
		uint32 uid = 12;
		string online_id = 7;
		ProfilePicture profile_picture = 2;
		uint32 add_score = 1;
		string _xbox_gamertag = 9;
		repeated uint32 OFEHCJOPEIG = 10;
		uint32 score = 3;
		string nickname = 14;
		repeated ExhibitionDisplayInfo card_list = 11;
	}
	uint32 IKLNEBCKENF = 4;
	uint32 difficulty_id = 13;
	repeated JOPDICINNLJ _settle_list = 2;
	repeated FGCJMIDEKMB GMNBBBOLHDH = 3;
	repeated uint32 MIFCBDAIKNH = 5;
	EACPNCPOKGE EBGPHJCLGKC = 14;
}
