// Recovered from _FairyTalesDetailInfoOuterClass.java's embedded descriptor; wire schema may predate 7.1.
syntax = "proto3";

package recovered.p__FairyTalesDetailInfo;
option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "_FairyTalesDetailInfoOuterClass";
import "DGAJHBBIDNM.proto";
import "JIEHJMIEHPM.proto";
import "MABDPGLBMOE.proto";
import "OICBFHCJGCC.proto";

message _FairyTalesDetailInfo {
  .recovered.p_DGAJHBBIDNM.DGAJHBBIDNM FBKBOIEBJCH = 1;
  repeated .JIEHJMIEHPM ICALMLAHAAL = 3;
  repeated .OICBFHCJGCC HIIIBLGMMLF = 6;
  repeated uint32 JLGIAAGNLCO = 9;
  repeated .MABDPGLBMOE PKAOIMANLKC = 13;
  bool ELCGFJCJMNN = 14;
}
