// Recovered from _LanternRiteV4DetailInfoOuterClass.java's embedded descriptor; wire schema may predate 7.1.
syntax = "proto3";

package recovered.p__LanternRiteV4DetailInfo;
option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "_LanternRiteV4DetailInfoOuterClass";
import "EIKPBFHDENP.proto";
import "LPDPPPHCNLA.proto";
import "NMGCANGGNKB.proto";

message _LanternRiteV4DetailInfo {
  .EIKPBFHDENP MIMIPBMJFEK = 5;
  .LPDPPPHCNLA BMMIHMMPHDD = 6;
  .NMGCANGGNKB IOLIBNOCBBB = 14;
}
