syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "_LeyLineChallengeDetailInfoOuterClass";

import "FAAOMPMEBKI.proto";
import "HDHLLCCCLJM.proto";
import "JJKBEPPIFIE.proto";
import "MKADIBABGKH.proto";

message _LeyLineChallengeDetailInfo {
	bool OFBDHIJICPL = 6;
	HDHLLCCCLJM FKGDIAPACDB = 50000;
	uint32 PIJLAHENJEP = 50001;
	bool LBCGNOOJDIC = 9;
	JJKBEPPIFIE ALJFGLAPKKM = 11;
	HDHLLCCCLJM IDIHOMKNMHE = 50002;
	uint64 LEEHFFLICIK = 7;
	repeated HDHLLCCCLJM HDAKHICDPPN = 5;
	repeated FAAOMPMEBKI AKLPNJCALKO = 13;
	uint32 GCONANDBHMP = 50003;
	repeated MKADIBABGKH difficulty_info_list = 14;
}
