// Recovered from _LostSamachurlDetailInfoOuterClass.java's embedded descriptor; wire schema may predate 7.1.
syntax = "proto3";

package recovered.p__LostSamachurlDetailInfo;
option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "_LostSamachurlDetailInfoOuterClass";
import "ENBLAIHHMMG.proto";
import "OGHIAGCBLJG.proto";

message _LostSamachurlDetailInfo {
  repeated .recovered.p_OGHIAGCBLJG.OGHIAGCBLJG ILIOIFMBIKB = 2;
  repeated .recovered.p_ENBLAIHHMMG.ENBLAIHHMMG DMKKMACCMBF = 15;
}
