// Recovered from _MultiCharacterDungeonSettleInfoOuterClass.java's embedded descriptor; wire schema may predate 7.1.
syntax = "proto3";

package recovered.p__MultiCharacterDungeonSettleInfo;
option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "_MultiCharacterDungeonSettleInfoOuterClass";
import "HJHAAMGJLKJ.proto";

message _MultiCharacterDungeonSettleInfo {
  uint32 level_id = 3;
  uint32 stage_id = 4;
  repeated uint32 JOPIGPEPHCN = 5;
  repeated .recovered.p_HJHAAMGJLKJ.HJHAAMGJLKJ team_info_list = 7;
  uint32 difficulty = 9;
  bool is_new_record = 14;
}
