// Recovered from _PenumbraAdventureDetailInfoOuterClass.java's embedded descriptor; wire schema may predate 7.1.
syntax = "proto3";

package recovered.p__PenumbraAdventureDetailInfo;
option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "_PenumbraAdventureDetailInfoOuterClass";
import "APGNMMCFCPD.proto";
import "GBAOLFCECGM.proto";
import "PKLEFDLHINI.proto";
import "_PenumbraAdventureFlightGearInfo.proto";
import "_PenumbraAdventureTargetShootingInfo.proto";

message _PenumbraAdventureDetailInfo {
  ._PenumbraAdventureFlightGearInfo _flight_gear_info = 3;
  .APGNMMCFCPD CLJOHONMNEH = 5;
  .recovered.p_PKLEFDLHINI.PKLEFDLHINI FBHDPNAJDJO = 6;
  ._PenumbraAdventureTargetShootingInfo _target_shooting_info = 7;
  .GBAOLFCECGM LLHAEBMBODJ = 13;
}
