syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "_RoleCombatSettleInfoOuterClass";

import "DIGMMKNOMJH.proto";
import "IGNEGGFGNHB.proto";
import "NBMAFDLIACA.proto";

message _RoleCombatSettleInfo {
	bool FBHFAMPKPPK = 9;
	DIGMMKNOMJH NAMEIDCGGIF = 13;
	uint32 coin_num = 4;
	bool INIDHGHIOOO = 1;
	repeated IGNEGGFGNHB HMINJJJIEBB = 3;
	uint32 difficulty_id = 11;
	repeated uint32 KNCAOGIMIJJ = 14;
	uint32 GBNCKPFLFIM = 15;
	uint32 use_time = 7;
	NBMAFDLIACA PEENJAIFAEN = 5;
	repeated uint64 HFDHOLOKLJK = 12;
	repeated uint64 avatar_guid_list = 8;
}
