syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "_TpsMercenariesSettleInfoOuterClass";

message _TpsMercenariesSettleInfo {
	uint32 difficulty = 15;
	uint32 BKLAKFGNCIH = 8;
	uint32 DLCKFLBGLPL = 5;
	uint32 KDLJHPGCKEK = 50000;
	uint32 use_time = 7;
	uint32 level_id = 11;
	bool is_new_record = 6;
	float LCGFBJHGFHF = 50001;
	uint32 GADNKLEDPAK = 50002;
	uint32 left_time = 3;
	uint32 ICLCODDOBDM = 4;
	bool ICBLEOKBPAJ = 10;
	float NBFANLFNCCO = 50003;
	uint32 score = 9;
	repeated uint32 FHINHGGMCEI = 1;
}
