syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "_UgcShortVideoBriefInfoOuterClass";

import "_UgcShortVideoAvatarInfo.proto";

message _UgcShortVideoBriefInfo {
	repeated uint32 avatar_id_list = 4;
	repeated uint32 LKCCHMHJNEF = 50000;
	repeated _UgcShortVideoAvatarInfo avatar_info_list = 12;
	bool FAAOOIKCIJO = 15;
	repeated uint32 KOKGKGKFDEI = 50001;
	repeated uint32 tag_list = 2;
	uint32 AAJNACIIKAD = 50002;
	uint32 level_id = 6;
	uint32 IILNHLANPGC = 50003;
	uint32 GLEEDODENBP = 50004;
	string _level_name = 14;
	string IONHLOONKFG = 5;
}
