syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "ActivityInfoOuterClass";

import "AcrobaticsBattleDetailInfo.proto";
import "ActivityMultiCharacterDetailInfo.proto";
import "ActivityPushTipsData.proto";
import "ActivityWatcherInfo.proto";
import "AdShootingDetailInfo.proto";
import "AkaFesDetailInfo.proto";
import "AlchemySimDetailInfo.proto";
import "AnimalViewDetailInfo.proto";
import "ArenaChallengeActivityDetailInfo.proto";
import "ArenaChallengeV5DetailInfo.proto";
import "AsterActivityDetailInfo.proto";
import "AutoTimeStopDetailInfo.proto";
import "BartenderActivityDetailInfo.proto";
import "BirdBallDetailInfo.proto";
import "BlessingActivityDetailInfo.proto";
import "BlitzRushActivityDetailInfo.proto";
import "BoltbugAbyssDetailInfo.proto";
import "BomberDodocoDetailInfo.proto";
import "BounceConjuringActivityDetailInfo.proto";
import "BrickBreakerDetailInfo.proto";
import "BubbleDramaDetailInfo.proto";
import "BubbleDramaPlayInfo.proto";
import "BulletHellDetailInfo.proto";
import "BuoyantCombatDetailInfo.proto";
import "CeremonyDetailInfo.proto";
import "ChannelerSlabActivityDetailInfo.proto";
import "CharAmusementDetailInfo.proto";
import "ChessActivityDetailInfo.proto";
import "CoinCollectDetailInfo.proto";
import "CollectUnderwaterDetailInfo.proto";
import "CookGameDetailInfo.proto";
import "CooperateChallengeDetailInfo.proto";
import "CrucibleActivityDetailInfo.proto";
import "CrystalLinkActivityDetailInfo.proto";
import "DeliveryActivityDetailInfo.proto";
import "DigActivityDetailInfo.proto";
import "DragonSpineActivityDetailInfo.proto";
import "DuelHeartDetailInfo.proto";
import "EchoShellDetailInfo.proto";
import "EffigyActivityDetailInfo.proto";
import "EffigyChallengeV2DetailInfo.proto";
import "EffigyChallengeV4DetailInfo.proto";
import "EffigyChallengeV5DetailInfo.proto";
import "ElectroherculesBattleDetailInfo.proto";
import "ElectroherculesBattleV3DetailInfo.proto";
import "ExpeditionActivityDetailInfo.proto";
import "FairyTalesDetailInfo.proto";
import "FilmfestDetailInfo.proto";
import "FindHilichurlDetailInfo.proto";
import "FishingJoyDetailInfo.proto";
import "FleurFairActivityDetailInfo.proto";
import "FleurFairV2DetailInfo.proto";
import "FlightActivityDetailInfo.proto";
import "FontaineGatherDetailInfo.proto";
import "FungusFighterDetailInfo.proto";
import "FungusFighterV2DetailInfo.proto";
import "FungusFighterV3DetailInfo.proto";
import "GCGFestivalDetailInfo.proto";
import "GachaActivityDetailInfo.proto";
import "GainBuffDetailInfo.proto";
import "GearActivityDetailInfo.proto";
import "GravenInnocenceDetailInfo.proto";
import "GreatFestivalV2DetailInfo.proto";
import "HachiActivityDetailInfo.proto";
import "HideAndSeekActivityDetailInfo.proto";
import "InstableSprayDetailInfo.proto";
import "IrodoriActivityDetailInfo.proto";
import "IslandPartyDetailInfo.proto";
import "JourneyDetailInfo.proto";
import "LanternRiteActivityDetailInfo.proto";
import "LanternRiteV4DetailInfo.proto";
import "LanternRiteV5DetailInfo.proto";
import "LimitedTimeRewardAreaBannerDetailInfo.proto";
import "LostSamachurlDetailInfo.proto";
import "LuminanceStoneChallengeActivityDetailInfo.proto";
import "LunaRiteDetailInfo.proto";
import "MichiaeMatsuriActivityDetailInfo.proto";
import "MikawaFlowerDetailInfo.proto";
import "MistTrialActivityDetailInfo.proto";
import "MonsterChessDetailInfo.proto";
import "MonsterVsMonsterDetailInfo.proto";
import "MoonfinTrialActivityDetailInfo.proto";
import "MuqadasPotionActivityDetailInfo.proto";
import "MusicGameActivityDetailInfo.proto";
import "NahidaBirthDetailInfo.proto";
import "NatlanArenaDetailInfo.proto";
import "NatlanDrillDetailInfo.proto";
import "NatlanRaceDetailInfo.proto";
import "NatlanTourDetailInfo.proto";
import "PartyDetailInfo.proto";
import "PenumbraAdventureDetailInfo.proto";
import "PhotoActivityDetailInfo.proto";
import "PhotoUnderseaDetailInfo.proto";
import "PlantFlowerActivityDetailInfo.proto";
import "PoetryFestivalDetailInfo.proto";
import "PotionActivityDetailInfo.proto";
import "QuickTimeCombatDetailInfo.proto";
import "RainbowPrinceDetailInfo.proto";
import "RechargeDiskDetailInfo.proto";
import "RockBoardExploreDetailInfo.proto";
import "RogueDiaryActivityDetailInfo.proto";
import "RoguelikeDungeonActivityDetailInfo.proto";
import "SalesmanActivityDetailInfo.proto";
import "SandwormCannonDetailInfo.proto";
import "SeaLampActivityDetailInfo.proto";
import "SeaLampActivityInfo.proto";
import "SeaLampV3DetailInfo.proto";
import "SlimeCannonDetailInfo.proto";
import "SorushTrialDetailInfo.proto";
import "SpiceActivityDetailInfo.proto";
import "StaminaFightDetailInfo.proto";
import "SummerTimeDetailInfo.proto";
import "SummerTimeV2DetailInfo.proto";
import "SumoActivityDetailInfo.proto";
import "TanukiTravelActivityDetailInfo.proto";
import "TeamChainDetailInfo.proto";
import "TowerChallengeDetailInfo.proto";
import "ToyBattleDetailInfo.proto";
import "TreasureHuntV4DetailInfo.proto";
import "TreasureMapActivityDetailInfo.proto";
import "TreasureSeelieActivityDetailInfo.proto";
import "TrialAvatarActivityDetailInfo.proto";
import "UgcActivityDetailInfo.proto";
import "UgcV2DetailInfo.proto";
import "VintageActivityDetailInfo.proto";
import "WaterSpiritActivityDetailInfo.proto";
import "WatergunDetailInfo.proto";
import "WindFieldDetailInfo.proto";
import "WinterCampActivityDetailInfo.proto";
import "_AdventurerStatueDetailInfo.proto";
import "_AquariumDetailInfo.proto";
import "_AutochessDetailInfo.proto";
import "_BlessingV2DetailInfo.proto";
import "_CatcafeDetailInfo.proto";
import "_ClientPlayCurLevelInfo.proto";
import "_ClientPlayData.proto";
import "_ColorBallDetailInfo.proto";
import "_DiversityBattleDetailInfo.proto";
import "_FishBlasterDetailInfo.proto";
import "_GCGAutoBattleCardDetailInfo.proto";
import "_GCGPveDetailInfo.proto";
import "_GCGPveInfiniteDetailInfo.proto";
import "_GCGPvePuzzleDetailInfo.proto";
import "_GoalChallengeDetailInfo.proto";
import "_HideAndSeekV4ActivityDetailInfo.proto";
import "_HolidayResortDetailInfo.proto";
import "_LanternRiteV6DetailInfo.proto";
import "_LeyLineChallengeDetailInfo.proto";
import "_LoliFriendDetailInfo.proto";
import "_MonsterChessV2DetailInfo.proto";
import "_Mvm2DetailInfo.proto";
import "_RankedMatchDetailInfo.proto";
import "_ShortVideoDetailInfo.proto";
import "_SnowRaceDetailInfo.proto";
import "_SumeruAdventureTrainingDetailInfo.proto";
import "_ThemeParkSimDetailInfo.proto";
import "_TowerDefenseDetailInfo.proto";
import "_TpsDefenseDetailInfo.proto";
import "_TradeShowDetailInfo.proto";
import "_WeekActiveDetailInfo.proto";

message ActivityInfo {
	oneof detail {
		SeaLampActivityDetailInfo sam_lamp_info = 1;
		CrucibleActivityDetailInfo crucible_info = 8;
		TrialAvatarActivityDetailInfo trial_avatar_info = 6;
		SalesmanActivityDetailInfo salesman_info = 15;
		PlantFlowerActivityDetailInfo plant_flower_info = 1276;
		GainBuffDetailInfo gain_buff_detail_info = 497;
		NatlanArenaDetailInfo natlan_arena_detail_info = 1033;
		LanternRiteActivityDetailInfo lantern_rite_activity_info = 16;
		FungusFighterV3DetailInfo fungus_fighter_v3_info = 1946;
		_MonsterChessV2DetailInfo monster_chess_v2_detail_info = 1307;
		QuickTimeCombatDetailInfo quick_time_combat_info = 427;
		DigActivityDetailInfo dig_info = 146;
		FairyTalesDetailInfo fairy_tales_detail_info = 1586;
		ArenaChallengeV5DetailInfo arena_challenge_v5_detail_info = 1584;
		SeaLampActivityInfo sea_lamp_info = 385;
		FindHilichurlDetailInfo find_hilichurl_info = 1521;
		FungusFighterDetailInfo fungus_fighter_info = 1780;
		LuminanceStoneChallengeActivityDetailInfo luminance_stone_challenge_info = 54;
		EffigyActivityDetailInfo effigy_info = 216;
		CoinCollectDetailInfo coin_collect_info = 1633;
		LimitedTimeRewardAreaBannerDetailInfo limited_time_reward_area_banner_info = 1628;
		FleurFairActivityDetailInfo fleur_fair_info = 1986;
		SorushTrialDetailInfo sorush_trial_info = 1160;
		RainbowPrinceDetailInfo rainbow_prince_detail_info = 899;
		_LoliFriendDetailInfo loli_friend_detail_info = 321;
		NahidaBirthDetailInfo nahida_birth_detail_info = 234;
		BirdBallDetailInfo bird_ball_detail_info = 506;
		_GCGPveInfiniteDetailInfo gcg_pve_infinite_info = 1548;
		IslandPartyDetailInfo island_party_info = 1550;
		MoonfinTrialActivityDetailInfo moonfin_trial_info = 1111;
		GreatFestivalV2DetailInfo great_festival_v2_detail_info = 369;
		_GoalChallengeDetailInfo goal_challenge_info = 815;
		_LanternRiteV6DetailInfo lantern_rite_v6_info = 250;
		_DiversityBattleDetailInfo diversity_battle_detail_info = 1870;
		PenumbraAdventureDetailInfo penumbra_adventure_info = 286;
		MonsterVsMonsterDetailInfo monster_vs_monster_detail_info = 898;
		MonsterChessDetailInfo monster_chess_detail_info = 2009;
		FilmfestDetailInfo filmfest_detail_info = 142;
		DeliveryActivityDetailInfo delivery_info = 1065;
		RogueDiaryActivityDetailInfo rogue_diary_info = 891;
		PhotoUnderseaDetailInfo photo_undersea_info = 2045;
		SeaLampV3DetailInfo sea_lamp_v3_info = 2020;
		_TowerDefenseDetailInfo tower_defense_detail_info = 169;
		BulletHellDetailInfo bullet_hell_detail_info = 1138;
		BrickBreakerDetailInfo brick_breaker_info = 643;
		TowerChallengeDetailInfo tower_challenge_detail_info = 641;
		_Mvm2DetailInfo mvm2_detail_info = 1377;
		_CatcafeDetailInfo catcafe_detail_info = 263;
		MistTrialActivityDetailInfo mist_trial_activity_info = 2025;
		SumoActivityDetailInfo sumo_info = 1049;
		_GCGPveDetailInfo gcg_pve_info = 1154;
		SummerTimeV2DetailInfo summer_time_v2_info = 1019;
		AdShootingDetailInfo ad_shooting_detail_info = 1088;
		BuoyantCombatDetailInfo buoyant_combat_info = 1965;
		_ThemeParkSimDetailInfo theme_park_sim_detail_info = 531;
		AutoTimeStopDetailInfo auto_time_stop_detail_info = 843;
		BomberDodocoDetailInfo bomber_dodoco_detail_info = 431;
		GearActivityDetailInfo gear_info = 812;
		EffigyChallengeV5DetailInfo effigy_challenge_v5_detail_info = 1686;
		CooperateChallengeDetailInfo cooperate_challenge_detail_info = 491;
		BartenderActivityDetailInfo bartender_info = 538;
		LostSamachurlDetailInfo lost_samachurl_info = 1312;
		ElectroherculesBattleDetailInfo electrohercules_battle_info = 984;
		AcrobaticsBattleDetailInfo acrobatics_battle_detail_info = 182;
		AkaFesDetailInfo aka_fes_info = 1125;
		AsterActivityDetailInfo aster_info = 1167;
		UgcActivityDetailInfo ugc_info = 1959;
		SummerTimeDetailInfo summer_time_info = 314;
		_TpsDefenseDetailInfo tps_defense_detail_info = 1224;
		RoguelikeDungeonActivityDetailInfo roguelike_dungoen_info = 1470;
		_HolidayResortDetailInfo holiday_resort_detail_info = 235;
		_SnowRaceDetailInfo snow_race_detail_info = 137;
		DragonSpineActivityDetailInfo dragon_spine_info = 1695;
		PhotoActivityDetailInfo photo_info = 546;
		_WeekActiveDetailInfo week_active_detail_info = 600;
		_LeyLineChallengeDetailInfo ley_line_challenge_detail_info = 1838;
		_BlessingV2DetailInfo blessing_v2_info = 1183;
		TreasureHuntV4DetailInfo treasure_hunt_v4_info = 1091;
		RechargeDiskDetailInfo recharge_disk_detail_info = 639;
		PartyDetailInfo party_detail_info = 1507;
		IrodoriActivityDetailInfo irodori_info = 1657;
		HideAndSeekActivityDetailInfo hide_and_seek_info = 57;
		_AquariumDetailInfo aquarium_detail_info = 526;
		FleurFairV2DetailInfo fleur_fair_v2_info = 633;
		GCGFestivalDetailInfo gcg_festival_info = 1261;
		_SumeruAdventureTrainingDetailInfo sumeru_adventure_training_detail_info = 914;
		CollectUnderwaterDetailInfo collect_underwater_info = 1466;
		WatergunDetailInfo watergun_info = 1248;
		PoetryFestivalDetailInfo poetry_festival_detail_info = 1604;
		ChessActivityDetailInfo chess_info = 567;
		SlimeCannonDetailInfo slime_cannon_detail_info = 1153;
		NatlanRaceDetailInfo natlan_race_info = 1246;
		StaminaFightDetailInfo stamina_fight_info = 190;
		WindFieldDetailInfo wind_field_info = 148;
		FishingJoyDetailInfo fishing_joy_detail_info = 1116;
		TreasureMapActivityDetailInfo treasure_map_info = 132;
		FungusFighterV2DetailInfo fungus_fighter_v2_info = 1671;
		BlitzRushActivityDetailInfo blitz_rush_info = 852;
		GachaActivityDetailInfo gacha_info = 1958;
		SpiceActivityDetailInfo spice_info = 824;
		BounceConjuringActivityDetailInfo bounce_conjuring_info = 274;
		ChannelerSlabActivityDetailInfo challneler_slab_info = 1000;
		AlchemySimDetailInfo alchemy_sim_detail_info = 1337;
		_TradeShowDetailInfo trade_show_detail_info = 67;
		_HideAndSeekV4ActivityDetailInfo hide_and_seek_v4_detail_info = 1054;
		BlessingActivityDetailInfo blessing_info = 2017;
		LanternRiteV5DetailInfo lantern_rite_v5_detail_info = 1763;
		_GCGPvePuzzleDetailInfo gcg_pve_puzzle_info = 777;
		CharAmusementDetailInfo char_amusement_info = 2003;
		EffigyChallengeV4DetailInfo effigy_challenge_v4_info = 1648;
		InstableSprayDetailInfo instable_spray_info = 728;
		NatlanTourDetailInfo natlan_tour_detail_info = 1753;
		_GCGAutoBattleCardDetailInfo gcg_auto_battle_card_detail_info = 421;
		BoltbugAbyssDetailInfo boltbug_abyss_detail_info = 511;
		JourneyDetailInfo journey_info = 1915;
		AnimalViewDetailInfo animal_view_info = 1660;
		_ColorBallDetailInfo color_ball_detail_info = 705;
		LanternRiteV4DetailInfo lantern_rite_v4_info = 62;
		TeamChainDetailInfo team_chain_info = 692;
		SandwormCannonDetailInfo sandworm_cannon_detail_info = 1625;
		ArenaChallengeActivityDetailInfo arena_challenge_info = 753;
		RockBoardExploreDetailInfo rock_board_explore_info = 90;
		CookGameDetailInfo cook_game_detail_info = 1812;
		WaterSpiritActivityDetailInfo water_spirit_info = 910;
		GravenInnocenceDetailInfo graven_innocence_info = 799;
		_RankedMatchDetailInfo ranked_match_detail_info = 778;
		DuelHeartDetailInfo duel_heart_info = 480;
		ExpeditionActivityDetailInfo expedition_info = 797;
		FontaineGatherDetailInfo fontaine_gather_info = 618;
		ActivityMultiCharacterDetailInfo activity_multi_character_info = 1293;
		NatlanDrillDetailInfo natlan_drill_info = 906;
		WinterCampActivityDetailInfo winter_camp_info = 1942;
		TanukiTravelActivityDetailInfo tanuki_travel_activity_info = 441;
		CeremonyDetailInfo ceremony_info = 217;
		TreasureSeelieActivityDetailInfo treasure_seelie_info = 1907;
		EchoShellDetailInfo echo_shell_info = 26;
		LunaRiteDetailInfo luna_rite_info = 1287;
		_AdventurerStatueDetailInfo adventurer_statue_detail_info = 164;
		HachiActivityDetailInfo hachi_info = 238;
		MusicGameActivityDetailInfo music_game_info = 168;
		EffigyChallengeV2DetailInfo effigy_challenge_info = 1209;
		CrystalLinkActivityDetailInfo crystal_link_info = 1359;
		ToyBattleDetailInfo toy_battle_info = 1141;
		PotionActivityDetailInfo potion_info = 992;
		MichiaeMatsuriActivityDetailInfo michiae_matsuri_info = 81;
		BubbleDramaDetailInfo bubble_drama_detail_info = 932;
		VintageActivityDetailInfo vintage_info = 318;
		_FishBlasterDetailInfo fish_blaster_info = 1340;
		UgcV2DetailInfo ugc_v2_info = 1748;
		_ShortVideoDetailInfo short_video_detail_info = 451;
		ElectroherculesBattleV3DetailInfo electrohercules_battle_v3_detail_info = 1279;
		FlightActivityDetailInfo flight_info = 1711;
		_AutochessDetailInfo autochess_info = 136;
		MuqadasPotionActivityDetailInfo muqadas_potion_info = 53;
		MikawaFlowerDetailInfo mikawa_flower_detail_info = 1689;
	}
	uint32 activity_type = 10;
	uint32 activity_id = 2;
	bool DPOHIMPNKIH = 50000;
	repeated uint32 meet_cond_list = 50001;
	bool BNIOBCBCGMC = 50002;
	repeated ActivityWatcherInfo watcher_info_list = 9;
	bool is_finished = 7;
	uint32 end_time = 14;
	repeated uint32 BFIDMPPFHHC = 50003;
	uint32 schedule_id = 3;
	uint32 begin_time = 4;
	bool is_quick_open = 1583;
	uint32 score_limit = 1424;
	repeated ActivityPushTipsData activity_push_tips_data_list = 1313;
	_ClientPlayData _client_play_data = 1850;
	map<uint32, uint32> wish_gift_num_map = 873;
	bool CMJNAFAKOCH = 50004;
	uint32 first_day_start_time = 113;
	repeated uint32 quick_open_pre_quest_list = 50005;
	uint32 DIEFHMGFNIJ = 50006;
	repeated uint32 taken_reward_list = 409;
	uint32 cur_score = 1673;
	uint32 BDOFMAKFCGO = 50007;
	map<uint32, uint32> activity_coin_map = 1715;
	bool is_hidden = 326;
	_ClientPlayCurLevelInfo _client_play_cur_level_info = 754;
	repeated uint64 OPCOMCJHGAJ = 1692;
	uint64 OPPDJKGIKBJ = 1204;
	BubbleDramaPlayInfo bubble_drama_play_info = 50008;
	bool FANKAEHKLBM = 50009;
}
