// Recovered from AddAranaraCollectionNotifyOuterClass.java's embedded descriptor; wire schema may predate 7.1.
syntax = "proto3";

package recovered.p_AddAranaraCollectionNotify;
option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "AddAranaraCollectionNotifyOuterClass";
import "AranaraCollectionState.proto";

message AddAranaraCollectionNotify {
  .recovered.p_AranaraCollectionState.AranaraCollectionState IPFPDNJPPPP = 14;
  .recovered.p_AranaraCollectionState.AranaraCollectionState OKGBACCFMKG = 15;
  uint32 collection_type = 2;
  uint32 collection_id = 4;
}
