syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "AkaFesDetailInfoOuterClass";

import "ANKDJAOILKB.proto";
import "DEDPANJOEAE.proto";
import "DOAKNFOOGMH.proto";
import "GKPJJJLDBOJ.proto";
import "ILHCGIIMHBM.proto";
import "MENHFPBEHLL.proto";

message AkaFesDetailInfo {
	ILHCGIIMHBM ACOACLMAJNM = 10;
	MENHFPBEHLL GFIMJAILAFF = 50000;
	DOAKNFOOGMH NJACKJJLCHN = 50001;
	DEDPANJOEAE pjciiiofmli = 50002;
	ANKDJAOILKB EGNIINEIJGB = 50003;
	GKPJJJLDBOJ ijgpjhppgmb = 50004;
}
