syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "AlchemySimDetailInfoOuterClass";

import "BBCHHKCMIOJ.proto";
import "CDOHBLNEKCJ.proto";
import "CKFHELMIGOP.proto";
import "GIMNDGBLHNL.proto";
import "GJFNDOODMCB.proto";
import "HMNAKLDLGGF.proto";
import "INNBIIAMPIJ.proto";
import "LGNCGIEICJJ.proto";
import "MKJLLPCIMCM.proto";

message AlchemySimDetailInfo {
	GIMNDGBLHNL hpmkggonkgp = 50000;
	GJFNDOODMCB hkkinpgdepc = 50001;
	MKJLLPCIMCM BJLMKGHFMDA = 15;
	CKFHELMIGOP PMMPDHCPONP = 14;
	BBCHHKCMIOJ basic_info = 11;
	repeated LGNCGIEICJJ NLKBEFDOFKN = 50002;
	repeated CDOHBLNEKCJ CCKABEMPMAP = 2;
	INNBIIAMPIJ hahnbkedick = 50003;
	HMNAKLDLGGF KLIJBFPJEDF = 50004;
}
