syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "AsterActivityDetailInfoOuterClass";

import "AsterLargeDetailInfo.proto";
import "AsterLittleDetailInfo.proto";
import "AsterMidDetailInfo.proto";
import "AsterProgressDetailInfo.proto";

message AsterActivityDetailInfo {
	AsterLittleDetailInfo aster_little = 2;
	uint32 BGHKDINALDB = 50000;
	bool is_special_reward_taken = 7;
	AsterMidDetailInfo aster_mid = 12;
	uint32 content_close_time = 13;
	uint32 DGBIKMCIGLN = 50001;
	AsterLargeDetailInfo aster_large = 6;
	bool is_content_closed = 11;
	AsterProgressDetailInfo aster_progress = 15;
}
