syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "AttackResultOuterClass";

import "AbilityIdentifier.proto";
import "AttackHitEffectResult.proto";
import "CIHENMDCMGJ.proto";
import "HIMBAGFLEHM.proto";
import "HitCollision.proto";
import "_EntityIntMotionInfo.proto";
import "Vector.proto";

message AttackResult {
	Vector NKCMIFFBMEN = 50000;
	uint32 attacker_id = 9;
	uint32 LNFCPOINHKK = 50001;
	uint32 element_type = 1;
	bool EPLABAAGCKE = 50002;
	HitCollision hit_collision = 4;
	int32 hit_retreat_angle_compat = 14;
	uint32 defense_id = 10;
	AbilityIdentifier ability_identifier = 7;
	AttackHitEffectResult hit_eff_result = 50003;
	float damage = 2;
	int32 AFPBFDHCDNK = 12;
	string anim_event_id = 5;
	uint32 EKDNPKHMJIE = 623;
	float OOFNGENKHKG = 50004;
	repeated uint32 OHPEIAGBOIK = 1313;
	bool GGAMPLOEPMG = 50005;
	float MDECMKGHDAK = 496;
	CIHENMDCMGJ EFBFOAOJADK = 1567;
	uint32 BNBBLJCDMPJ = 1975;
	float MDBPICGKMLB = 50006;
	uint32 JCPDJCGGJCC = 50007;
	uint32 FDEGAMMGNGI = 50008;
	uint32 MHJDKCODNAA = 50009;
	uint32 GMNALDFDANK = 50010;
	float NILAPFIGLLH = 50011;
	bool PKOFLCBFEOA = 50012;
	uint32 IFHJIFEBKAO = 50013;
	uint32 CFKHDFPCHCL = 50014;
	uint32 PLNPCMILPPD = 50015;
	float NJFMEBDIICN = 50016;
	HIMBAGFLEHM PGPBACPJGNM = 425;
	uint32 JILIGGDCLDH = 748;
	_EntityIntMotionInfo _int_motion_info = 50017;
	bool DMIEAHDCHFA = 50018;
	Vector DNMDKFFCNPJ = 50019;
	bool OMJGKPMPFBI = 50020;
	uint32 BJHAEPGOAKM = 50021;
	uint32 MOEKEMAHBNN = 50022;
	uint32 IDENIGMCBJB = 50023;
}
