syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "AvatarDataNotifyOuterClass";

import "AvatarInfo.proto";
import "AvatarRenameInfo.proto";
import "AvatarTeam.proto";

message AvatarDataNotify {
	repeated uint32 owned_flycloak_list = 50000;
	repeated AvatarInfo avatar_list = 7;
	uint32 cur_avatar_team_id = 3;
	repeated AvatarRenameInfo avatar_rename_list = 14;
	repeated uint32 owned_costume_list = 50001;
	repeated uint32 _owned_trace_effect_list = 50002;
	repeated uint32 backup_avatar_team_order_list = 1;
	map<uint32, AvatarTeam> avatar_team_map = 8;
	uint64 choose_avatar_guid = 9;
	repeated uint64 temp_avatar_guid_list = 12;
}
