syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "AvatarLifeStateChangeNotifyOuterClass";

import "PlayerDieType.proto";
import "ServerBuff.proto";

message AvatarLifeStateChangeNotify {
	uint32 life_state = 8;
	uint64 avatar_guid = 7;
	uint32 move_reliable_seq = 5;
	PlayerDieType die_type = 10;
	string attack_tag = 14;
	repeated ServerBuff server_buff_list = 6;
	repeated string EEOIMNHKALK = 15;
	uint32 source_entity_id = 13;
	uint32 LDAODDFLPGB = 11;
	uint32 client_sequence_id = 4;
}
