// Recovered from BeyondSceneAvatarCosmeticUpdateNotifyOuterClass.java's embedded descriptor; wire schema may predate 7.1.
syntax = "proto3";

package recovered.p_BeyondSceneAvatarCosmeticUpdateNotify;
option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "BeyondSceneAvatarCosmeticUpdateNotifyOuterClass";
import "BeyondCosmeticPlan.proto";

message BeyondSceneAvatarCosmeticUpdateNotify {
  uint64 avatar_guid = 8;
  repeated .recovered.p_BeyondCosmeticPlan.BeyondCosmeticPlan alt_cosmetic_plan = 10;
}
