syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "CKFHELMIGOPOuterClass";

import "PJFELCMPMKJ.proto";

message CKFHELMIGOP {
	uint64 OAICLPJOICK = 50000;
	uint32 FLGHAOCLOAJ = 12;
	uint32 DILPAMLKLCC = 50001;
	uint32 IECDLMNALEJ = 50002;
	map<uint64, uint32> CCKHKMBCEGJ = 50003;
	uint64 MIHDAJBFNKE = 50004;
	repeated uint32 KNPJGLLICAD = 11;
	map<uint64, uint32> CGNCCOMCOBA = 50005;
	uint32 JLCDGPLJJMM = 50006;
	uint32 NDLKHEFOAJF = 50007;
	repeated PJFELCMPMKJ DDNFEHGKHFO = 15;
}
