syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "CoinCollectLevelDataOuterClass";

import "CoinCollectTeamInfoData.proto";

message CoinCollectLevelData {
	bool DEELGNJPPHJ = 50000;
	bool MHKPMMIOIFO = 50001;
	CoinCollectTeamInfoData single_best_team_info = 12;
	uint32 level_id = 10;
	uint32 CLLFHBFHJFB = 50002;
	uint32 FIJFFHDFDLI = 50003;
	bool njjlelknfpl = 50004;
	uint32 oidegdjmaah = 50005;
	uint32 nobhhoiapmm = 50006;
	bool is_level_open = 8;
	repeated CoinCollectTeamInfoData double_best_team_info_list = 5;
	uint32 MCGGMMLPIJP = 50007;
}
