syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "CoopChapterOuterClass";

import "CoopCg.proto";
import "CoopPoint.proto";
import "CoopReward.proto";

message CoopChapter {
	enum State {
		STATE_CLOSE = 0;
		STATE_COND_NOT_MEET = 1;
		STATE_COND_MEET = 2;
		STATE_ACCEPT = 3;
	}
	map<uint32, uint32> seen_ending_map = 12;
	repeated uint32 ODECGJCJBAB = 50000;
	uint32 total_end_count = 50001;
	State state = 5;
	uint32 finished_end_count = 50002;
	uint32 id = 10;
	repeated uint32 JKAGGEGDKOH = 50003;
	repeated uint32 lock_reason_list = 50004;
	repeated CoopPoint coop_point_list = 8;
	repeated CoopCg coop_cg_list = 4;
	repeated CoopReward coop_reward_list = 9;
}
