syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "CPKAFPOGJKNOuterClass";

import "DACMDDCLPNH.proto";

message CPKAFPOGJKN {
	uint32 KOEKLGJJJKI = 50000;
	bool EIBFFKFHDOJ = 50001;
	uint32 OADOGGFPLAJ = 11;
	uint32 upgrade_level = 3;
	DACMDDCLPNH CCIIPCGDMIM = 50002;
	uint32 GJKEOFMEJKB = 50003;
	repeated uint32 MOLFPGIEHLM = 9;
	uint32 NONHKCOBFKM = 50004;
	uint32 ECIPNPDCCJM = 50005;
	bool KPJLFMDDPMK = 50006;
	uint32 EFDAONILFMD = 50007;
	DACMDDCLPNH FGBOIBJOHAE = 50008;
}
