syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "DungeonPlayerDieNotifyOuterClass";

import "AbilityString.proto";
import "PlayerDieType.proto";
import "StrengthenPointData.proto";

message DungeonPlayerDieNotify {
	oneof entity {
		uint32 gadget_id = 11;
		uint32 monster_id = 5;
	}
	PlayerDieType die_type = 9;
	uint32 murderer_entity_id = 50000;
	uint32 AOMDIHGJMNK = 50001;
	AbilityString cfadgphidli = 14;
	uint32 revive_count = 12;
	map<uint32, StrengthenPointData> strengthen_point_data_map = 6;
	uint32 OBOKABMLGHI = 50002;
	uint32 dungeon_id = 2;
	uint32 wait_time = 7;
}
