syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "DungeonSettleNotifyOuterClass";

import "BladeDanceSettleInfo.proto";
import "ChannellerSlabLoopDungeonResultInfo.proto";
import "CrystalLinkDungeonSettleInfo.proto";
import "DungeonSettleExhibitionInfo.proto";
import "EffigyChallengeDungeonResultInfo.proto";
import "EffigyChallengeV2SettleInfo.proto";
import "FungusFighterV2SettleInfo.proto";
import "InstableSprayDungeonSettleInfo.proto";
import "MultiCharacterDungeonSettleInfo.proto";
import "PacmanSettleInfo.proto";
import "ParamList.proto";
import "RoguelikeDungeonSettleInfo.proto";
import "StrengthenPointData.proto";
import "SummerTimeV2DungeonSettleInfo.proto";
import "TeamChainSettleInfo.proto";
import "TowerLevelEndNotify.proto";
import "TrialAvatarFirstPassDungeonNotify.proto";
import "WindFieldDungeonSettleInfo.proto";
import "_AcrobaticsBattleSettleInfo.proto";
import "_AdShootingSettleInfo.proto";
import "_AdventurerStatueDungeonSettleInfo.proto";
import "_AquariumDivingDungeonSettleInfo.proto";
import "_AquariumFishingDungeonSettleInfo.proto";
import "_AutoTimeStopSettleInfo.proto";
import "_BadgetBattleSettleInfo.proto";
import "_BladeHeartDungeonSettleInfo.proto";
import "_BomberDodocoSettleInfo.proto";
import "_BulletHellSettleInfo.proto";
import "_CeremonyBattleSettleInfo.proto";
import "_CharMasterSettleInfo.proto";
import "_CooperateChallengeSettleInfo.proto";
import "_DiversityBattleSettleInfo.proto";
import "_EffigyChallengeV5SettleInfo.proto";
import "_FairyTalesCombatSettleInfo.proto";
import "_FeverBattleSettleInfo.proto";
import "_FilmfestBattleSettleInfo.proto";
import "_FilmfestSniperSettleInfo.proto";
import "_FungusFighterV3SettleInfo.proto";
import "_GainBuffSettleInfo.proto";
import "_GalleryContextEntry.proto";
import "_GoalChallengeSettleInfo.proto";
import "_HumanDragonPuzzleSettleInfo.proto";
import "_InspirationSpurtDungeonSettleInfo.proto";
import "_LanternRiteV6BattleSettleInfo.proto";
import "_LanternRiteV6ParkourSettleInfo.proto";
import "_LoliBattleDungeonSettleInfo.proto";
import "_LoliGolfDungeonSettleInfo.proto";
import "_LoliRunDungeonSettleInfo.proto";
import "_LostSamachurlSneakSettleInfo.proto";
import "_MapMarkSettleInfo.proto";
import "_MistTrialSettleInfo.proto";
import "_MonsterSnapSettleInfo.proto";
import "_MusicPartySettleInfo.proto";
import "_Mvm2PveSettleInfo.proto";
import "_Mvm2SimulateSettleInfo.proto";
import "_NatlanArenaSettleInfo.proto";
import "_NatlanDragonPartySettleInfo.proto";
import "_NatlanDrillBattleSettleInfo.proto";
import "_NodkraiTourHackSettleInfo.proto";
import "_NodkraiTourParkourSettleInfo.proto";
import "_OneShotDungeonSettleInfo.proto";
import "_QuickTimeCombatSettleInfo.proto";
import "_RankedMatchPuzzleSettleInfo.proto";
import "_RankedMatchShootingSettleInfo.proto";
import "_RankedMatchSnowBallSettleInfo.proto";
import "_RankedMatchTrainSettleInfo.proto";
import "_RechargeDiskSettleInfo.proto";
import "_RoleCombatSettleInfo.proto";
import "_Saurus1V3SettleInfo.proto";
import "_ShortVideoSettleInfo.proto";
import "_SlimeCannonSettleInfo.proto";
import "_SnowRaceCombatSettleInfo.proto";
import "_SnowRaceParkourSettleInfo.proto";
import "_SnowRaceThrowSettleInfo.proto";
import "_StaminaFightSettleInfo.proto";
import "_SumeruAdventureTrainingSettleInfo.proto";
import "_ThemeParkParkourSettleInfo.proto";
import "_ThemeParkTriathlonSettleInfo.proto";
import "_TowerChallengeSettleInfo.proto";
import "_TowerDefenseSettleInfo.proto";
import "_TpsDefenseSettleInfo.proto";
import "_TpsMercenariesSettleInfo.proto";
import "_TradeShowBattleSettleInfo.proto";
import "_TradeShowStgSettleInfo.proto";
import "_TradeShowTdSettleInfo.proto";

message DungeonSettleNotify {
	oneof detail {
		_NatlanDrillBattleSettleInfo natlan_drill_battle_settle_info = 1760;
		_TowerChallengeSettleInfo tower_challenge_settle_info = 1363;
		RoguelikeDungeonSettleInfo roguelike_dungeon_settle_info = 542;
		_AutoTimeStopSettleInfo auto_time_stop_settle_info = 186;
		_SnowRaceParkourSettleInfo snow_race_parkour_settle_info = 595;
		_NodkraiTourParkourSettleInfo nodkrai_tour_parkour_settle_info = 684;
		_NatlanDragonPartySettleInfo natlan_dragon_party_settle_info = 594;
		_NodkraiTourHackSettleInfo nodkrai_tour_hack_settle_info = 1876;
		_AdShootingSettleInfo ad_shooting_settle_info = 1364;
		InstableSprayDungeonSettleInfo instable_spray_settle_info = 327;
		_Mvm2SimulateSettleInfo mvm2_simulate_settle_info = 1587;
		_BomberDodocoSettleInfo bomber_dodoco_settle_info = 705;
		_TradeShowBattleSettleInfo trade_show_battle_settle_info = 141;
		_RechargeDiskSettleInfo recharge_disk_settle_info = 1941;
		_RoleCombatSettleInfo role_combat_settle_info = 42;
		_StaminaFightSettleInfo stamina_fight_settle_info = 1761;
		_AcrobaticsBattleSettleInfo acrobatics_battle_settle_info = 1322;
		_CharMasterSettleInfo char_master_settle_info = 1212;
		_FilmfestSniperSettleInfo filmfest_sniper_settle_info = 811;
		_CeremonyBattleSettleInfo ceremony_battle_settle_info = 932;
		_GainBuffSettleInfo gain_buff_settle_info = 68;
		WindFieldDungeonSettleInfo wind_field_dungeon_settle_info = 751;
		_SnowRaceCombatSettleInfo snow_race_combat_settle_info = 1184;
		TeamChainSettleInfo team_chain_settle_info = 283;
		_RankedMatchSnowBallSettleInfo ranked_match_snow_ball_settle_info = 1438;
		_RankedMatchShootingSettleInfo ranked_match_shooting_settle_info = 1862;
		_MusicPartySettleInfo music_party_settle_info = 1240;
		MultiCharacterDungeonSettleInfo multi_character_dungeon_settle_info = 73;
		_NatlanArenaSettleInfo natlan_arena_settle_info = 108;
		_GalleryContextEntry gallery_context_entry = 1786;
		_TpsMercenariesSettleInfo tps_mercenaries_settle_info = 638;
		_CooperateChallengeSettleInfo cooperate_challenge_settle_info = 784;
		BladeDanceSettleInfo blade_dance_settle_info = 337;
		EffigyChallengeV2SettleInfo effigy_challenge_v2_settle_info = 1821;
		TowerLevelEndNotify tower_level_end_notify = 1536;
		_RankedMatchPuzzleSettleInfo ranked_match_puzzle_settle_info = 1972;
		_AdventurerStatueDungeonSettleInfo adventurer_statue_dungeon_settle_info = 1883;
		_FilmfestBattleSettleInfo filmfest_battle_settle_info = 1223;
		_RankedMatchTrainSettleInfo ranked_match_train_settle_info = 1752;
		_TowerDefenseSettleInfo tower_defense_settle_info = 1521;
		_SumeruAdventureTrainingSettleInfo sumeru_adventure_training_settle_info = 2039;
		PacmanSettleInfo pacman_settle_info = 1985;
		_LoliGolfDungeonSettleInfo loli_golf_dungeon_settle_info = 1657;
		_ThemeParkParkourSettleInfo theme_park_parkour_settle_info = 1808;
		_Saurus1V3SettleInfo saurus1v3_settle_info = 178;
		_EffigyChallengeV5SettleInfo effigy_challenge_v5_settle_info = 1850;
		_LostSamachurlSneakSettleInfo lost_samachurl_sneak_settle_info = 1558;
		_MistTrialSettleInfo mist_trial_settle_info = 1646;
		EffigyChallengeDungeonResultInfo effigy_challenge_dungeon_result_info = 65;
		_OneShotDungeonSettleInfo one_shot_dungeon_settle_info = 417;
		_BladeHeartDungeonSettleInfo blade_heart_dungeon_settle_info = 555;
		_Mvm2PveSettleInfo mvm2_pve_settle_info = 952;
		_LanternRiteV6BattleSettleInfo lantern_rite_v6_battle_settle_info = 1414;
		SummerTimeV2DungeonSettleInfo summer_time_v2_dungeon_settle_info = 1700;
		_DiversityBattleSettleInfo diversity_battle_settle_info = 1541;
		_LanternRiteV6ParkourSettleInfo lantern_rite_v6_parkour_settle_info = 678;
		_BulletHellSettleInfo bullet_hell_settle_info = 1730;
		_ThemeParkTriathlonSettleInfo theme_park_triathlon_settle_info = 1588;
		_AquariumDivingDungeonSettleInfo aquarium_diving_dungeon_settle_info = 883;
		_AquariumFishingDungeonSettleInfo aquarium_fishing_dungeon_settle_info = 1183;
		_MapMarkSettleInfo map_mark_settle_info = 575;
		_GoalChallengeSettleInfo goal_challenge_settle_info = 1626;
		_SnowRaceThrowSettleInfo snow_race_throw_settle_info = 1799;
		_FeverBattleSettleInfo fever_battle_settle_info = 130;
		_FairyTalesCombatSettleInfo fairy_tales_combat_settle_info = 1251;
		CrystalLinkDungeonSettleInfo crystal_link_settle_info = 1320;
		_ShortVideoSettleInfo short_video_settle_info = 1262;
		_BadgetBattleSettleInfo badget_battle_settle_info = 1565;
		_MonsterSnapSettleInfo monster_snap_settle_info = 2003;
		_TpsDefenseSettleInfo tps_defense_settle_info = 664;
		_QuickTimeCombatSettleInfo quick_time_combat_settle_info = 1725;
		ChannellerSlabLoopDungeonResultInfo channeller_slab_loop_dungeon_result_info = 1213;
		_TradeShowTdSettleInfo trade_show_td_settle_info = 1722;
		TrialAvatarFirstPassDungeonNotify trial_avatar_first_pass_dungeon_notify = 1806;
		FungusFighterV2SettleInfo fungus_fighter_v2_settle_info = 792;
		_LoliBattleDungeonSettleInfo loli_battle_dungeon_settle_info = 234;
		_SlimeCannonSettleInfo slime_cannon_settle_info = 16;
		_LoliRunDungeonSettleInfo loli_run_dungeon_settle_info = 538;
		_InspirationSpurtDungeonSettleInfo inspiration_spurt_dungeon_settle_info = 235;
		_TradeShowStgSettleInfo trade_show_stg_settle_info = 782;
		_FungusFighterV3SettleInfo fungus_fighter_v3_settle_info = 1934;
		_HumanDragonPuzzleSettleInfo human_dragon_puzzle_settle_info = 632;
	}
	uint32 result = 7;
	uint32 use_time = 6;
	map<uint32, StrengthenPointData> strengthen_point_data_map = 2;
	uint32 close_time = 11;
	map<uint32, ParamList> settle_show = 8;
	repeated uint32 player_uid_list = 15;
	repeated uint32 fail_cond_list = 14;
	uint32 create_player_uid = 1;
	repeated DungeonSettleExhibitionInfo exhibition_info_list = 5;
	uint32 dungeon_id = 10;
	bool is_success = 13;
}
