// Recovered from DungeonCandidateTeamPlayerStateOuterClass.java's embedded descriptor; wire schema may predate 7.1.
syntax = "proto3";

package recovered.p_DungeonCandidateTeamPlayerState;
option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "DungeonCandidateTeamPlayerStateOuterClass";

enum DungeonCandidateTeamPlayerState {
  DungeonCandidateTeamPlayerState_IDLE = 0;
  DungeonCandidateTeamPlayerState_CHANGING_AVATAR = 1;
  DungeonCandidateTeamPlayerState_READY = 2;
}
