syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "EntityFightPropChangeReasonNotifyOuterClass";

import "ChangeEnergyReason.proto";
import "ChangeHpDebtsReason.proto";
import "ChangeHpReason.proto";
import "JMPGPKCBGKP.proto";
import "PropChangeReason.proto";

message EntityFightPropChangeReasonNotify {
	ChangeEnergyReason change_energy_reson = 8;
	uint32 EFIBMPKIJJH = 3;
	ChangeHpReason change_hp_reason = 15;
	uint32 entity_id = 10;
	JMPGPKCBGKP detail_info = 12;
	float prop_delta = 5;
	float _paid_hp_debts = 4;
	ChangeHpDebtsReason _change_hp_debts_reason = 6;
	uint32 prop_type = 9;
	repeated uint32 param_list = 2;
	PropChangeReason reason = 1;
}
