syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "EvtAvatarEnterFocusNotifyOuterClass";

import "ForwardType.proto";
import "Vector.proto";

message EvtAvatarEnterFocusNotify {
	int32 IMMFFEBPCJM = 12;
	bool ogolkmlffhe = 50000;
	bool CFNHGMLGPHP = 50001;
	ForwardType forward_type = 15;
	bool gmlebihpokd = 50002;
	bool HFFPEFBLBPC = 50003;
	bool mdmoimdcopf = 50004;
	bool egblcmolomc = 50005;
	bool dbphfokbncp = 50006;
	bool oemkcenfmim = 50007;
	bool ADMFCLBHILF = 50008;
	uint32 entity_id = 10;
	bool FDCDPKDKNAL = 50009;
	Vector focus_forward = 9;
	bool pbhffghhpma = 50010;
}
