syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "EvtBulletHitNotifyOuterClass";

import "ForwardType.proto";
import "HitColliderType.proto";
import "Vector.proto";

message EvtBulletHitNotify {
	uint32 single_bullet_id = 50000;
	uint32 entity_id = 13;
	int32 hit_box_index = 10;
	HitColliderType hit_collider_type = 4;
	uint32 hit_entity_id = 50001;
	uint32 forward_peer = 2;
	Vector hit_point = 11;
	ForwardType forward_type = 3;
	Vector hit_normal = 6;
}
