syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "EvtCreateGadgetNotifyOuterClass";

import "AbilityString.proto";
import "CEAFBJOBFJE.proto";
import "ForwardType.proto";
import "LifeByOwnerType.proto";
import "Vector.proto";

message EvtCreateGadgetNotify {
	uint32 camp_id = 7;
	bool LMLMALLLGBB = 50000;
	Vector init_euler_angles = 8;
	Vector init_pos = 15;
	uint32 config_id = 11;
	uint64 guid = 13;
	uint32 target_entity_id = 10;
	uint32 owner_entity_id = 6;
	uint32 room_id = 5;
	ForwardType forward_type = 9;
	uint32 entity_id = 3;
	bool PBLACGNNCDF = 50001;
	uint32 camp_type = 2;
	uint32 AAMABJDMIFN = 14;
	uint32 prop_owner_entity_id = 1;
	uint32 KMDOFBPMGAI = 80;
	int32 local_id = 1451;
	bool NHNFGNMNDDE = 50002;
	bool is_peer_id_from_player = 141;
	repeated uint32 target_lock_point_index_list = 226;
	CEAFBJOBFJE BHJNCGINIJB = 1732;
	LifeByOwnerType _life_by_owner_type = 1925;
	repeated uint32 target_entity_id_list = 1121;
	uint32 LDAODDFLPGB = 1349;
	uint32 born_slot_index = 421;
	AbilityString ability_name = 988;
	uint32 init_pose_id = 810;
}
