syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "FHDOGFCDKDKOuterClass";

import "OLNDJCHOPMC.proto";
import "ProfilePicture.proto";
import "Uint32Pair.proto";
import "Vector.proto";

message FHDOGFCDKDK {
	Vector HAAJBIJNMCJ = 6;
	repeated OLNDJCHOPMC KJIJEGKMFIE = 12;
	ProfilePicture profile_picture = 3;
	string nick_name = 7;
	uint32 uid = 15;
	uint32 progress = 1;
	uint32 score = 13;
	uint32 FPDGAPADCDK = 8;
	repeated OLNDJCHOPMC PDNALAKIIKL = 5;
	uint32 finish_time = 10;
	repeated Uint32Pair AABFCMMGMKE = 9;
	uint32 HBCLKADPLED = 2;
	string _xbox_gamertag = 4;
	string online_id = 14;
}
