syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "FleurFairActivityDetailInfoOuterClass";

import "FleurFairChapterInfo.proto";
import "FleurFairDungeonSectionInfo.proto";
import "FleurFairMinigameInfo.proto";

message FleurFairActivityDetailInfo {
	uint32 GHFCHBJDKGC = 50000;
	bool is_content_closed = 10;
	bool is_dungeon_unlocked = 7;
	repeated FleurFairChapterInfo chapter_info_list = 14;
	uint32 content_close_time = 5;
	map<uint32, FleurFairDungeonSectionInfo> dungeon_section_info_map = 15;
	uint32 IOKLANDHJAP = 50001;
	map<uint32, FleurFairMinigameInfo> minigame_info_map = 12;
}
