syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "GAALHKEALCNOuterClass";

import "NMPMEMFEOMA.proto";
import "ShowAvatarInfo.proto";

message GAALHKEALCN {
	uint32 level_id = 4;
	uint32 EGGHBMLGLHC = 7;
	repeated uint32 ODGDINNDMGE = 3;
	repeated NMPMEMFEOMA EPLCNHFNDPA = 8;
	repeated ShowAvatarInfo show_avatar_info_list = 9;
	uint32 DEADDOKKEHM = 2;
	repeated uint32 AGFGCHIHNEE = 5;
	bool is_finish = 11;
	uint32 cost_time = 13;
	bool OGBLPLNCKIF = 6;
	bool is_open = 12;
	uint32 AKCPFFADDOP = 1;
}
