syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "GadgetInteractReqOuterClass";

import "InterOpType.proto";
import "ResinCostType.proto";

message GadgetInteractReq {
	// Local 7.1 type 25686 / writer 0x14f662a90; unidentified semantics keep native names.
	bool KHBHECKFAFO = 1;
	bool NEPAHMPCHGA = 3;
	uint32 gadget_id = 4;
	bool DAELLCLGEAL = 5;
	bool GGNGMJDNJKE = 6;
	ResinCostType resin_cost_type = 7;
	InterOpType op_type = 9;
	uint32 DDDHMAOFKED = 10;
	uint32 gadget_entity_id = 11;
	uint32 KGLMOAAIOML = 12;
	bool EPANKHIHBDJ = 13;
	uint32 BOMAJJOKCCN = 14;
	bool GHDMNALCIFD = 15;
}
