syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "GadgetInteractReqOuterClass";

import "InterOpType.proto";
import "ResinCostType.proto";

message GadgetInteractReq {
	bool AJDBEGMCGKD = 13;
	ResinCostType resin_cost_type = 7;
	uint32 EBEELPIEKEL = 14;
	bool HDJABIODGCI = 50000;
	bool DOGHJJCHDLF = 50001;
	uint32 gadget_entity_id = 11;
	bool LPCDPGNKGFL = 50002;
	uint32 gadget_id = 4;
	uint32 CJIPKAIPCIB = 10;
	bool IKMNHOHNBKJ = 50003;
	bool IKDIFBEOEKM = 50004;
	InterOpType op_type = 9;
	uint32 ALLPOOBNNPH = 12;
}
