syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "GAGPIICGHOFOuterClass";

import "BCJLBJFFJPK.proto";
import "DAFKLLCCHJJ.proto";
import "DIHEGEGCPFP.proto";
import "EABNOCBCGFM.proto";
import "EEEPOOPKBPC.proto";
import "EJCHPEFKGLJ.proto";
import "EMOEJGGBAIG.proto";
import "HDNLDEHMAJP.proto";
import "IHCIBFKMHBD.proto";
import "LBBDOIMGFNI.proto";
import "NNGBNNMJABP.proto";

message GAGPIICGHOF {
	NNGBNNMJABP KPOOPDCNAFE = 15;
	uint32 BGLEEKPNKCB = 13;
	uint32 KDFOECAIJPD = 50000;
	uint32 LBOODPMIDLI = 50001;
	uint32 JGNEMBNBDAB = 50002;
	DAFKLLCCHJJ ABKKKKCIDPA = 50003;
	HDNLDEHMAJP KNDJAHOCOKB = 11;
	repeated EABNOCBCGFM PJBHIMEHLKM = 1;
	EEEPOOPKBPC MAANAIMHCIK = 8;
	LBBDOIMGFNI GCPNMNAAPFM = 50004;
	BCJLBJFFJPK ALMLCEKAANG = 9;
	EJCHPEFKGLJ IDKFENOLMJD = 2;
	EMOEJGGBAIG goal = 7;
	IHCIBFKMHBD MOJJDHBMODD = 50005;
	bool LIKMFJBNGFI = 14;
	uint32 GAODBDDJOAC = 50006;
	uint32 IHHLKCEBFKL = 50007;
	repeated DIHEGEGCPFP AENACNIBHBN = 666;
	repeated uint32 FDKKJIIIGEP = 469;
}
