syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "GetPlayerTokenRspOuterClass";

import "StopServerInfo.proto";

message GetPlayerTokenRsp {
	bytes security_cmd_buffer = 50000;
	string msg = 11;
	string account_uid = 2;
	uint32 uid = 13;
	int32 retcode = 10;
	bytes extra_bin_data = 9;
	uint32 gm_uid = 50001;
	uint32 platform_type = 8;
	string token = 4;
	string secret_key = 12;
	bool is_proficient_player = 50002;
	uint32 black_uid_end_time = 1;
	uint32 account_type = 50003;
	bool is_guest = 6;
	uint64 secret_key_seed = 15;
	uint32 reg_platform = 50004;
	string server_rand_key = 554;
	bool CGPIOKGGDPB = 50005;
	string _xuid = 463;
	string birthday = 1351;
	uint32 tag = 343;
	uint32 authkey_ver = 50006;
	uint32 minors_reg_min_age = 1913;
	uint32 sub_channel_id = 50007;
	string auth_appid = 1662;
	bytes _security_file = 50008;
	string sign = 487;
	bool KONAINKDJCN = 50009;
	string client_version_random_key = 1981;
	bool MGNAAEGCEDL = 50010;
	repeated uint32 finish_collection_id_list = 567;
	string country_code = 1817;
	string psn_id = 297;
	uint32 channel_id = 1072;
	StopServerInfo stop_server = 1501;
	string client_ip_str = 1603;
	string game_biz = 1198;
	string authkey = 844;
	string _client_version = 1856;
	uint32 key_id = 427;
	uint32 sign_type = 50011;
}
