syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "GetScenePointRspOuterClass";

message GetScenePointRsp {
	bool is_relogin = 10;
	repeated uint32 unlocked_point_list = 6;
	int32 retcode = 1;
	repeated uint32 JHHBKAOPBAH = 50000;
	repeated uint32 unlock_area_list = 12;
	repeated uint32 IEMCNADNPED = 50001;
	repeated uint32 unhide_point_list = 50002;
	repeated uint32 group_unlimit_point_list = 50003;
	repeated uint32 OLEEDBKCAAN = 50004;
	uint32 scene_id = 11;
	uint32 belong_uid = 8;
	repeated uint32 hide_point_list = 4;
	repeated uint32 locked_point_list = 50005;
}
