syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "GravenInnocenceDetailInfoOuterClass";

import "GravenInnocenceCampInfo.proto";
import "GravenInnocenceCarveInfo.proto";
import "GravenInnocencePhotoInfo.proto";
import "GravenInnocenceRaceInfo.proto";

message GravenInnocenceDetailInfo {
	bool is_content_closed = 7;
	GravenInnocenceCarveInfo carve_info = 8;
	GravenInnocencePhotoInfo photo_info = 2;
	GravenInnocenceRaceInfo race_info = 10;
	GravenInnocenceCampInfo camp_info = 11;
}
