// Recovered from HomeLimitedShopGoodsOuterClass.java's embedded descriptor; wire schema may predate 7.1.
syntax = "proto3";

package recovered.p_HomeLimitedShopGoods;
option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "HomeLimitedShopGoodsOuterClass";
import "ItemParam.proto";

message HomeLimitedShopGoods {
  .ItemParam goods_item = 12;
  repeated .ItemParam cost_item_list = 11;
  uint32 buy_limit = 10;
  uint32 disable_type = 14;
  uint32 goods_id = 9;
  uint32 bought_num = 13;
}
