syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "HomeSceneArrangementInfoOuterClass";

import "HomeBlockArrangementInfo.proto";
import "HomeFurnitureData.proto";
import "MLLBFLGFLDN.proto";
import "Vector.proto";

message HomeSceneArrangementInfo {
	repeated HomeBlockArrangementInfo block_arrangement_info_list = 1;
	uint32 scene_id = 13;
	repeated HomeFurnitureData stair_list = 50000;
	Vector IILKHACKPAI = 50001;
	HomeFurnitureData main_house = 10;
	Vector born_pos = 14;
	bool KGGKIAHPDGO = 50002;
	uint32 bgm_id = 4;
	Vector djinn_pos = 9;
	Vector KAPPOHDCAKP = 3;
	uint32 tmp_version = 7;
	uint32 comfort_value = 15;
	bool OADJEMPMKIF = 50003;
	repeated HomeFurnitureData door_list = 50004;
	Vector MEEACPBAEJN = 50005;
	repeated MLLBFLGFLDN CKDKECLLALB = 1071;
}
