// Recovered from HuntingOfferDataOuterClass.java's embedded descriptor; wire schema may predate 7.1.
syntax = "proto3";

package recovered.p_HuntingOfferData;
option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "HuntingOfferDataOuterClass";
import "HuntingPair.proto";
import "HuntingOfferState.proto";

message HuntingOfferData {
  .recovered.p_HuntingPair.HuntingPair hunting_pair = 7;
  .recovered.p_HuntingOfferState.HuntingOfferState state = 5;
  uint32 city_id = 15;
}
