// Recovered from JFEBHPOHIBEOuterClass.java's embedded descriptor; wire schema may predate 7.1.
syntax = "proto3";

package recovered.p_JFEBHPOHIBE;
option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "JFEBHPOHIBEOuterClass";

enum JFEBHPOHIBE {
  JFEBHPOHIBE_GCG_LEVEL_NONE = 0;
  JFEBHPOHIBE_GCG_LEVEL_CONST = 1;
  JFEBHPOHIBE_GCG_LEVEL_WEEK = 2;
  JFEBHPOHIBE_GCG_LEVEL_WORLD = 3;
  JFEBHPOHIBE_GCG_LEVEL_BOSS = 4;
  JFEBHPOHIBE_GCG_LEVEL_CHARACTER = 5;
  JFEBHPOHIBE_GCG_LEVEL_BREAK = 6;
  JFEBHPOHIBE_GCG_LEVEL_QUEST = 7;
  JFEBHPOHIBE_GCG_LEVEL_GUIDE_GROUP = 8;
  JFEBHPOHIBE_GCG_LEVEL_OTHER = 9;
  JFEBHPOHIBE_GCG_LEVEL_JOURNEY = 10;
  JFEBHPOHIBE_GCG_LEVEL_PVE = 11;
  JFEBHPOHIBE_GCG_LEVEL_PVE_INFINITE = 12;
  JFEBHPOHIBE_GCG_LEVEL_PVE_PUZZLE = 13;
}
