syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "JJKBEPPIFIEOuterClass";

import "HDHLLCCCLJM.proto";
import "JPLNCOKGBBG.proto";
import "PPOBOBDKPHI.proto";

message JJKBEPPIFIE {
	repeated JPLNCOKGBBG ABPMPKBOINH = 15;
	uint32 EBMOODIKLDM = 6;
	bool KOMPLLJLEOL = 8;
	uint32 DEADDOKKEHM = 12;
	uint32 FIDIFABIGBH = 4;
	PPOBOBDKPHI OFCFHPFDGLD = 7;
	uint64 JLAMEIEBIHO = 9;
	repeated HDHLLCCCLJM NFNDONBDLJA = 2;
	repeated HDHLLCCCLJM OPMOMHOOMAA = 5;
	uint32 NNPHIFOPPKO = 3;
}
