// Recovered from LOODODEGNOHOuterClass.java's embedded descriptor; wire schema may predate 7.1.
syntax = "proto3";

package recovered.p_LOODODEGNOH;
option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "LOODODEGNOHOuterClass";
import "DANBHHLJLLA.proto";
import "ILOLNEALMDN.proto";

message LOODODEGNOH {
  repeated .recovered.p_DANBHHLJLLA.DANBHHLJLLA KEBKELKNABD = 14;
  repeated .recovered.p_ILOLNEALMDN.ILOLNEALMDN MJONNGLEPLE = 15;
  repeated .recovered.p_ILOLNEALMDN.ILOLNEALMDN CEHOCMODGHM = 3;
  repeated uint32 JKPPHFIKJDC = 7;
}
