// Recovered from MaterialDeleteReturnNotifyOuterClass.java's embedded descriptor; wire schema may predate 7.1.
syntax = "proto3";

package recovered.p_MaterialDeleteReturnNotify;
option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "MaterialDeleteReturnNotifyOuterClass";
import "MaterialDeleteReturnType.proto";

message MaterialDeleteReturnNotify {
  map<uint32, uint32> HFAHLONBGKL = 12;
  map<uint32, uint32> NCDHBPLKPHB = 13;
  .recovered.p_MaterialDeleteReturnType.MaterialDeleteReturnType type = 15;
}
