syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "MCBCGPMDIFIOuterClass";

import "FNMMKAMBICN.proto";
import "JPGDPIOHKOL.proto";

message MCBCGPMDIFI {
	repeated JPGDPIOHKOL level_info_list = 15;
	bool GFMDMENKALA = 50000;
	repeated uint32 NGNKDNFOPDB = 50001;
	repeated uint32 MFKFEOAALPN = 50002;
	bool EIFNKICAKCO = 50003;
	uint32 IKBLLCLNBLH = 50004;
	repeated uint32 EMPMBEDABCD = 50005;
	uint32 IBNKIJCDIKK = 50006;
	repeated FNMMKAMBICN FECECFDPFBP = 9;
	bool EFIHHNEAFAK = 50007;
	repeated uint32 OODMCABNGPE = 50008;
}
