// Recovered from MIBBLDJIBHOOuterClass.java's embedded descriptor; wire schema may predate 7.1.
syntax = "proto3";

package recovered.p_MIBBLDJIBHO;
option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "MIBBLDJIBHOOuterClass";
import "NFICKHNFNLN.proto";

message MIBBLDJIBHO {
  repeated .recovered.p_NFICKHNFNLN.NFICKHNFNLN DFJKAHIIDNL = 11;
  uint32 OMEBOHLACPH = 15;
  bool is_open = 1;
  bool is_finish = 14;
  uint32 JNBGBHPMIEI = 5;
  uint32 level_id = 13;
  uint32 PLAJDMMKEPL = 6;
}
