syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "MKJLLPCIMCMOuterClass";

import "AHKBALPHAAB.proto";
import "_TemplatePotionInfo.proto";

message MKJLLPCIMCM {
	uint32 BMFLNENJCCJ = 50000;
	uint32 GLNPCFFJOMK = 50001;
	uint32 PABCOFFLFMF = 50002;
	uint32 PFGKLKDGKNI = 50003;
	repeated _TemplatePotionInfo NFCHLDDOALL = 11;
	uint32 CPLCJCLPOPH = 50004;
	AHKBALPHAAB ELKDIMBAEPJ = 1;
	uint32 OICBPFABKFM = 50005;
	uint32 ACJECNOJOBP = 50006;
	bool GHEDNNPDEMO = 15;
	_TemplatePotionInfo BNDLHOBBABM = 9;
	uint32 IDBAEDDIAGI = 3;
}
