// Recovered from MusicGameSettleReqOuterClass.java's embedded descriptor; wire schema may predate 7.1.
syntax = "proto3";

package recovered.p_MusicGameSettleReq;
option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "MusicGameSettleReqOuterClass";

message MusicGameSettleReq {
  uint32 correct_hit = 7;
  repeated uint32 OEAHADEGEOA = 327;
  uint64 ugc_guid = 1;
  bool BPNLLFDJJOL = 1200;
  uint32 score = 8;
  uint32 MECALGKAKJK = 14;
  uint32 max_combo = 2;
  repeated uint32 KPPICEDHMPN = 5;
  float speed = 1628;
  uint32 KDAOEDCLEFG = 1749;
  bool is_save_score = 6;
  bool MAMHOPGFOKD = 1198;
  uint32 NMPPJPOJFDC = 4;
  uint32 music_basic_id = 11;
  uint32 combo = 9;
  uint32 NGALDEAEBHG = 15;
  uint32 FCFNKIDLDHJ = 938;
  uint32 GDOMKIHOKCC = 747;
}
