syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "OMNMAIIHHDJOuterClass";

import "FIIHDNCNDHH.proto";
import "OLNDJCHOPMC.proto";
import "Uint32Pair.proto";

message OMNMAIIHHDJ {
	bool FHIOEKBKAJF = 1;
	uint64 HALOGJLKGLB = 6;
	repeated FIIHDNCNDHH record_list = 2;
	uint32 PDDGCIDOLBL = 50000;
	uint32 IKADJGPFNOI = 50001;
	repeated Uint32Pair KEJAEGGMIBJ = 5;
	repeated Uint32Pair AABFCMMGMKE = 9;
	bool is_open = 13;
	uint32 HBCLKADPLED = 15;
	repeated OLNDJCHOPMC PDNALAKIIKL = 8;
}
