syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "ParentQuestOuterClass";

import "CKKMPKBFBDP.proto";
import "ChildQuest.proto";
import "InferencePageInfo.proto";
import "ParentQuestRandomInfo.proto";

message ParentQuest {
	bool is_finished = 4;
	uint32 accept_time = 15;
	repeated CKKMPKBFBDP GFFBOKNBJLC = 9;
	repeated InferencePageInfo inference_page_list = 2;
	repeated int32 quest_var = 11;
	repeated ChildQuest child_quest_list = 13;
	bool is_random = 12;
	uint32 quest_var_seq = 50000;
	uint32 parent_quest_state = 50001;
	ParentQuestRandomInfo random_info = 8;
	uint64 video_key = 50002;
	uint32 parent_quest_id = 14;
	map<uint32, uint32> time_var_map = 1;
	bool DDHKDIOKFIF = 7;
	bool _is_focus_mode = 10;
}
