syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "PenumbraAdventureDetailInfoOuterClass";

import "APGNMMCFCPD.proto";
import "GBAOLFCECGM.proto";
import "HFLCFLBGIKI.proto";
import "_PenumbraAdventureFlightGearInfo.proto";
import "_PenumbraAdventureTargetShootingInfo.proto";

message PenumbraAdventureDetailInfo {
	_PenumbraAdventureFlightGearInfo _flight_gear_info = 13;
	APGNMMCFCPD CLJOHONMNEH = 50000;
	HFLCFLBGIKI lkjafjofkjf = 50001;
	_PenumbraAdventureTargetShootingInfo _target_shooting_info = 9;
	GBAOLFCECGM LLHAEBMBODJ = 11;
}
