// Recovered from PhotoUnderseaInfoOuterClass.java's embedded descriptor; wire schema may predate 7.1.
syntax = "proto3";

package recovered.p_PhotoUnderseaInfo;
option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "PhotoUnderseaInfoOuterClass";
import "MGIHJDAHEAB.proto";
import "JKKBIKPIANF.proto";

message PhotoUnderseaInfo {
  repeated .recovered.p_MGIHJDAHEAB.MGIHJDAHEAB object_info_list = 5;
  repeated .recovered.p_JKKBIKPIANF.JKKBIKPIANF level_info_list = 15;
}
