syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "PlayerLoginReqOuterClass";

import "ALFKEHMLFLO.proto";
import "FNGEEAFJCDG.proto";
import "_Vector2Int.proto";

message PlayerLoginReq {
	bool is_guest = 14;
	uint32 platform_type = 8;
	uint32 target_uid = 6;
	string device_uuid = 50000;
	string platform = 10;
	string token = 3;
	string system_version = 50001;
	string client_version = 11;
	uint32 language_type = 1;
	string device_name = 50002;
	uint64 login_rand = 13;
	string device_info = 5;
	uint32 account_type = 50003;
	string account_uid = 2;
	bool is_editor = 15;
	uint32 NBFMNCMEHGM = 50004;
	string cps = 50005;
	ALFKEHMLFLO DFNBAFNKCED = 1358;
	_Vector2Int IHMDHCDBHDJ = 1724;
	bool CEADLMGKJMP = 50006;
	uint32 channel_id = 672;
	string _xuid = 1041;
	string checksum = 279;
	string psn_id = 1441;
	uint32 timestamp = 1552;
	uint32 reg_platform = 50007;
	bool CGMBIAPFHGE = 1368;
	string online_id = 1047;
	uint32 gm_uid = 50008;
	string security_library_md5 = 50009;
	uint32 tag = 1665;
	FNGEEAFJCDG KJEMCDAJINF = 1065;
	string ECJHHHKAFIO = 50010;
	uint32 sub_channel_id = 50011;
	bytes security_cmd_reply = 50012;
	bytes extra_bin_data = 745;
	uint32 cloud_client_ip = 671;
	string _xbox_gamertag = 499;
	uint32 MCKNOBKGGEM = 50013;
	string country_code = 2019;
	uint32 HPHGKOCDPJE = 50014;
	string birthday = 1105;
	string checksum_client_version = 50015;
	bool LFABPIKDHKL = 50016;
	string OMBBHFFLNIM = 50017;
	uint32 HENDBLEDPIG = 50018;
	string PMBCMNHEGHO = 50019;
	uint32 ALMPHOAOJEC = 479;
	uint32 KDIKBHLPKDJ = 50020;
	uint32 client_data_version = 1440;
	string BKIICHHOJAF = 912;
	string PDDPLNEPLJJ = 50021;
	string client_verison_hash = 50022;
	bytes environment_error_code = 50023;
}
