syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "PlayerEnterSceneNotifyOuterClass";

import "EnterType.proto";
import "MKCENPDADHA.proto";
import "MapLayerInfo.proto";
import "PIJIEDJBGCN.proto";
import "Vector.proto";
import "_LimitedRegionInfo.proto";
import "_MirrorWorldSceneDetail.proto";

message PlayerEnterSceneNotify {
	repeated uint32 scene_tag_id_list = 5;
	uint32 scene_id = 9;
	uint32 world_level = 7;
	Vector prev_pos = 50000;
	uint32 prev_scene_id = 50001;
	Vector pos = 8;
	EnterType type = 10;
	uint32 enter_scene_token = 1;
	uint64 scene_begin_time = 14;
	uint32 target_uid = 12;
	bool DGILMKBJBMH = 50002;
	uint32 dungeon_id = 4;
	uint32 _template_loading_id = 1814;
	uint32 enter_reason = 339;
	_LimitedRegionInfo _limited_region_info = 1144;
	string scene_transaction = 1248;
	uint32 _dungeon_difficulty_type = 50003;
	uint32 BGICEPHCGEO = 50004;
	PIJIEDJBGCN PCBFOAKLMKG = 960;
	MKCENPDADHA HBCAHGNHINM = 1048;
	_MirrorWorldSceneDetail _mirror_world_scene_detail = 1287;
	MapLayerInfo _map_layer_info = 1217;
	Vector ALLIIBMKFLN = 50005;
	uint32 create_player_uid = 1368;
	bool FKICGIHNPOI = 50006;
	uint32 world_type = 864;
}
