syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "PlayerLoginRspOuterClass";

import "BlockInfo.proto";
import "FNGEEAFJCDG.proto";
import "FeatureBlockInfo.proto";
import "MPGPEKAFHJG.proto";
import "NGKOPBGLDJM.proto";
import "ResVersionConfig.proto";
import "ShortAbilityHashPair.proto";
import "StopServerInfo.proto";

message PlayerLoginRsp {
	bool is_relogin = 14;
	bool GHAJDNKLEDA = 50000;
	uint32 ohmigaflnid = 50001;
	uint64 login_rand = 7;
	map<string, int32> ability_hash_map = 8;
	string game_biz = 11;
	bool is_use_ability_hash = 50002;
	uint32 client_data_version = 13;
	uint32 client_silence_data_version = 15;
	uint32 target_uid = 4;
	int32 ability_hash_code = 10;
	bytes player_data = 3;
	int32 retcode = 9;
	bool GICKBBGJGCK = 50003;
	bytes sc_info = 1743;
	string client_version_suffix = 50004;
	ResVersionConfig next_res_version_config = 1984;
	string birthday = 1312;
	map<uint32, BlockInfo> block_info_map = 1205;
	bool CGMBIAPFHGE = 1508;
	repeated ShortAbilityHashPair short_ability_hash_map = 625;
	map<uint64, MPGPEKAFHJG> KKNBKGBLHDM = 1549;
	uint32 AMBIGCMFEIM = 50005;
	ResVersionConfig res_version_config = 1911;
	StopServerInfo nfachcnjogl = 50006;
	string client_silence_version_suffix = 50007;
	bool is_sc_open = 50008;
	bool OEMHPIKBDMB = 50009;
	string register_cps = 790;
	string msg = 1066;
	FNGEEAFJCDG KJEMCDAJINF = 21;
	string country_code = 342;
	bool KLKDKMBAPGA = 50010;
	string next_resource_url = 55;
	string client_md5 = 50011;
	NGKOPBGLDJM LPFKKMMLFOP = 368;
	uint32 ALMPHOAOJEC = 1123;
	bool is_audit = 1329;
	repeated FeatureBlockInfo feature_block_info_list = 50012;
	double total_tick_time = 755;
	uint32 platform_type = 492;
	string client_silence_md5 = 50013;
	bool MBPNFGLAJOG = 653;
}
