syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "QueryPathRspOuterClass";

import "BEIKOGGHFHD.proto";
import "Vector.proto";

message QueryPathRsp {
	enum PathStatusType {
		PathStatusType_STATUS_FAIL = 0;
		PathStatusType_STATUS_SUCC = 1;
		PathStatusType_STATUS_PARTIAL = 2;
	}
	PathStatusType query_status = 10;
	int32 retcode = 14;
	int32 query_id = 6;
	int32 FBLCJIHADLH = 15;
	repeated BEIKOGGHFHD INAAJKIFKIF = 2;
	repeated Vector corners = 3;
}
