syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "QuickUseWidgetRspOuterClass";

import "ClientCollectorData.proto";
import "OneoffGatherPointDetectorData.proto";
import "SkyCrystalDetectorQuickUseResult.proto";
import "_ClientDetectorResult.proto";

message QuickUseWidgetRsp {
	oneof param {
		OneoffGatherPointDetectorData detector_data = 8;
		ClientCollectorData client_collector_data = 13;
		SkyCrystalDetectorQuickUseResult sky_crystal_detector_quick_use_result = 16371;
		_ClientDetectorResult client_detector_result = 17204;
	}
	uint32 material_id = 9;
	uint32 KHEMKPBBNHC = 3;
	int32 retcode = 2;
}
