syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "RoguelikeDungeonActivityDetailInfoOuterClass";

import "RogueStageInfo.proto";
import "RoguelikeShikigamiRecord.proto";

message RoguelikeDungeonActivityDetailInfo {
	bool is_content_closed = 2;
	uint32 content_close_time = 9;
	repeated RoguelikeShikigamiRecord shikigami_list = 8;
	repeated uint32 rune_list = 4;
	repeated uint32 equipped_rune_list = 11;
	repeated RogueStageInfo stage_list = 3;
}
