syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "SalesmanActivityDetailInfoOuterClass";

import "SalesmanStatusType.proto";

message SalesmanActivityDetailInfo {
	bool CCIDPKHDGLB = 50000;
	SalesmanStatusType status = 10;
	map<uint32, uint32> selected_reward_id_map = 4;
	uint32 FNPCMPBIIMP = 50001;
	bool LOCIIDPOHAH = 50002;
	uint32 KMKFHBKGBOH = 50003;
	uint32 IKCLPCPHAJF = 9;
	uint32 DILMJEONOCC = 50004;
	uint32 KFEIFMLHHGM = 50005;
	uint32 day_index = 15;
}
