syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "SaveUgcReqOuterClass";

import "KLALGJNDAFD.proto";
import "UgcMusicBriefInfo.proto";
import "UgcMusicRecord.proto";
import "UgcType.proto";
import "_UgcLanV5CardBriefInfo.proto";
import "_UgcLanV5CardRecord.proto";
import "_UgcShortVideoRecord.proto";

message SaveUgcReq {
	oneof record {
		UgcMusicRecord music_record = 12;
		_UgcLanV5CardRecord lan_v5_card_record = 9;
		_UgcShortVideoRecord short_video_record = 8;
	}
	oneof brief {
		UgcMusicBriefInfo music_brief_info = 438;
		_UgcLanV5CardBriefInfo lan_v5_card_brief_info = 1169;
	}
	UgcType ugc_type = 4;
	KLALGJNDAFD ugcType_x = 10;
	uint32 schedule_id = 2;
}
