syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "SceneTeamAvatarOuterClass";

import "AbilityControlBlock.proto";
import "AbilitySyncStateInfo.proto";
import "AvatarInfo.proto";
import "SceneAvatarInfo.proto";
import "SceneEntityInfo.proto";
import "SceneWeaponInfo.proto";
import "ServerBuff.proto";

message SceneTeamAvatar {
	bool is_reconnect = 3;
	bool is_player_cur_avatar = 50000;
	AbilitySyncStateInfo avatar_ability_info = 50001;
	uint32 weapon_entity_id = 12;
	AbilityControlBlock ability_control_block = 11;
	AvatarInfo avatar_info = 4;
	uint32 player_uid = 13;
	uint32 entity_id = 8;
	AbilitySyncStateInfo weapon_ability_info = 50002;
	repeated ServerBuff server_buff_list = 9;
	SceneEntityInfo scene_entity_info = 15;
	uint64 avatar_guid = 5;
	SceneAvatarInfo scene_avatar_info = 1;
	uint32 scene_id = 6;
	uint64 weapon_guid = 7;
	repeated SceneWeaponInfo DGGJCMNHDOJ = 382;
	bool is_on_scene = 50003;
}
