syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "ShopGoodsOuterClass";

import "AOGBDADBNNH.proto";
import "ItemParam.proto";

message ShopGoods {
	uint32 bought_num = 13;
	repeated uint32 MEODDILKAAD = 50000;
	ItemParam goods_item = 2;
	repeated ItemParam cost_item_list = 8;
	uint32 goods_id = 5;
	uint32 min_level = 50001;
	uint32 max_level = 1;
	uint32 ELPGDNACFOA = 50002;
	uint32 next_refresh_time = 10;
	uint32 end_time = 12;
	uint32 mcoin = 50003;
	uint32 hcoin = 6;
	uint32 OCFMGIPGLDK = 50004;
	uint32 scoin = 50005;
	uint32 begin_time = 4;
	uint32 HBFOJABHIND = 50006;
	uint32 discount_begin_time = 50007;
	uint32 AJCBLGEDLFK = 50008;
	uint32 single_limit = 50009;
	bool NGPHJJIEDEH = 50010;
	repeated uint32 MMMFLNHEDNI = 1158;
	uint32 LDCJFLOPNMP = 66;
	repeated uint32 AIALJDFIEAI = 50011;
	uint32 EKBHAAKJINF = 50012;
	repeated AOGBDADBNNH KAGKMENGAFH = 1701;
	bool MBMIKDBJNAN = 50013;
	uint32 discount_end_time = 50014;
	uint32 DCMBDJMCGGP = 50015;
}
