syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "TowerAllDataRspOuterClass";

import "TowerCurLevelRecord.proto";
import "TowerFloorRecord.proto";
import "TowerMonthlyBrief.proto";

message TowerAllDataRsp {
	enum _TowerSkipFloorState {
		TOWER_SKIP_FLOOR_STATE_NONE = 0;
		TOWER_SKIP_FLOOR_STATE_CAN_NOT_SKIP = 1;
		TOWER_SKIP_FLOOR_STATE_HAS_REWARD = 2;
		TOWER_SKIP_FLOOR_STATE_TAKEN_REWARD = 3;
	}
	uint32 tower_schedule_id = 50000;
	uint32 EFABCDDNIFA = 50001;
	uint32 next_schedule_change_time = 50002;
	int32 retcode = 15;
	TowerCurLevelRecord cur_level_record = 13;
	uint32 commemorative_reward_id = 50003;
	map<uint32, uint32> skip_floor_granted_reward_item_map = 50004;
	bool is_finished_entrance_floor = 10;
	map<uint32, uint32> floor_open_time_map = 50005;
	bool is_first_interact = 12;
	uint32 valid_tower_record_num = 50006;
	uint32 skip_to_floor_index = 50007;
	repeated TowerFloorRecord tower_floor_record_list = 11;
	uint32 GKIFECKDHKD = 50008;
	TowerMonthlyBrief monthly_brief = 8;
	_TowerSkipFloorState _tower_skip_floor_state = 209;
	uint32 schedule_start_time = 50009;
	TowerMonthlyBrief last_schedule_monthly_brief = 315;
}
