syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "TrialAvatarActivityRewardDetailInfoOuterClass";

message TrialAvatarActivityRewardDetailInfo {
	repeated uint32 _passed_training_step_list = 50000;
	bool _is_avatar_owned = 50001;
	uint32 reward_id = 2;
	bool passed_dungeon = 50002;
	bool received_reward = 50003;
	bool is_can_take_reward = 8;
	repeated uint32 _available_training_step_list = 50004;
	uint32 trial_avatar_index_id = 14;
	bool _is_skip_training = 50005;
}
