syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "UgcMusicBriefInfoOuterClass";

import "_MusicGameSocial.proto";

message UgcMusicBriefInfo {
	uint32 max_score = 9;
	string creator_nickname = 11;
	bool is_psn_platform = 1;
	uint32 version = 3;
	bool is_played = 5;
	uint32 music_id = 12;
	uint32 save_time = 2;
	uint64 ugc_guid = 6;
	uint32 jbgofomfahf = 50000;
	uint32 LDDCHDFKLGO = 50001;
	bool is_changed_after_publish = 10;
	bool is_published = 7;
	uint32 KFHNNAIABLG = 50002;
	uint32 publish_time = 8;
	uint64 import_from_ugc_guid = 14;
	repeated uint32 _beatmap_category_id_list = 265;
	repeated uint32 CCJOGFPEKID = 50003;
	_MusicGameSocial social = 1314;
	uint32 HHBOBIJKFPJ = 50004;
	uint32 PGHGCGNLNPG = 166;
	uint32 IIPJKAOBBBD = 50005;
	uint32 MOIDOMCHPFG = 50006;
	repeated uint32 COAEPKLMKPE = 50007;
	uint32 NLCMMJILBKJ = 50008;
	uint32 MLAJCIMGINA = 1425;
}
