syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "VintageMarketInfoOuterClass";

import "VintageMarketDealInfo.proto";
import "VintageMarketStoreInfo.proto";

message VintageMarketInfo {
	repeated uint32 AMOAMHMFPJE = 50000;
	map<uint32, bool> bargain_info_map = 12;
	bool LCBHLDGCDOJ = 50001;
	bool JIMBIKEHCHI = 50002;
	bool pjdgihdipfp = 50003;
	uint32 JDPHFJIIPAB = 50004;
	repeated uint32 bpghmofcodi = 50005;
	repeated uint32 FIEEOEHEEHP = 50006;
	bool PBDCICBAKEA = 50007;
	repeated uint32 ICAGNFOEFIB = 6;
	VintageMarketDealInfo deal_info = 4;
	repeated VintageMarketStoreInfo open_store_list = 15;
	uint32 store_round = 14;
	bool cefffakmcde = 50008;
	uint32 ILEKNBEOBOG = 50009;
	uint32 help_skill_id = 1035;
	repeated uint32 PHKDBBBLAEE = 50010;
	uint32 OGPLNOGAOGB = 50011;
	bool GFADKEIEMJI = 50012;
	bool JLDIGMDFJFL = 50013;
	uint32 HJJABBNNCIA = 50014;
	bool JOMKHCMAPLM = 50015;
}
