syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "WinterCampActivityDetailInfoOuterClass";

import "ItemParam.proto";
import "WinterCampRaceStageInfo.proto";
import "WinterCampStageInfo.proto";

message WinterCampActivityDetailInfo {
	repeated WinterCampRaceStageInfo race_info_list = 5;
	repeated uint32 CNLIGPFPPDC = 50000;
	repeated uint32 LFFBHOJNFDO = 50001;
	repeated ItemParam used_item_list = 10;
	WinterCampStageInfo explore_info = 13;
	repeated uint32 dmjdfjojofj = 50002;
	WinterCampStageInfo battle_info = 11;
	bool is_content_closed = 15;
}
